version: '3.7'
services:
  # db server
  manage-subs-mysql:
    image: mysql:5.7
    container_name: manage-subs-mysql
    environment:
      MYSQL_USER: osamura
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      TZ: 'Asis/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --wait_timeout=28800
    volumes:
      - ./mysql/data:/var/lib/mysql/data
    ports:
      - 4406:4406

  # API esrver
  manage-subs-api:
    container_name: manage-subs-api
    stdin_open: true
    tty: true
    command: /bin/bash
    build:
      context: .
      dockerfile: ./app/Dockerfile
    # command: pipenv run tests
    volumes:
      - ./:/app
    ports:
      - 2000:8080
    depends_on:
      - 'manage-subs-mysql'
    env_file:
      - ./.env